### ISSUE TITLE
Backend Data Issues

### ISSUE THREAD

**Issue by albertkun** [LACMTA/gopass-lookup#14]
## Update from 8/3

Hello @matikin9 ! Here are my updates for review!

<ol class="vicinity rich-diff-level-zero" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; margin-left: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="unchanged rich-diff-level-one" style="box-sizing: border-box;">Occasionally a school will have two records, only the contact information changes, for example:</li></ol><div class="expandable unchanged js-expandable rich-diff-level-zero" style="box-sizing: border-box; margin-bottom: 0px !important; margin-left: 16px; color: rgb(14, 17, 22); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 class="unchanged rich-diff-level-one" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25;">Example 1</h3>

District | School | Address | City | State | Zip Code | Telephone | Participating
-- | -- | -- | -- | -- | -- | -- | --
Charter | Alliance Gertz-Ressler Richard Merkin 6-12 Complex | 2023 South Union Avenue | Los Angeles | CA | 90007 | (213) 745-8141 | TRUE
Charter | Alliance Gertz-Ressler Richard Merkin 6-12 Complex | 2023 South Union Avenue | Los Angeles | CA | 90007 | (213) 748-0141 | TRUE

<ol start="2" class="unchanged rich-diff-level-one" style="box-sizing: border-box; padding-left: 2em; margin-top: 0px; margin-bottom: 16px; list-style-type: decimal;"><li class="unchanged" style="box-sizing: border-box;">School names are different than in the California data set, for example,<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">109th Street Elementary</code><span> </span>is<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">One Hundred Nineth Street Elementary</code>, this is also the official spelling:<span> </span><a href="https://109street-lausd-ca.schoolloop.com/" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none;">https://109street-lausd-ca.schoolloop.com/</a></li><li class="unchanged" style="box-sizing: border-box; margin-top: 0.25em;">Differences in address formatting,<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">south</code><span> </span>vs.<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">s</code><span> </span>and<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">Mc Kinley</code><span> </span>vs.<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">McKinley</code>, the<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">McKinley</code><span> </span>is also the official spelling on the website.</li><li class="unchanged" style="box-sizing: border-box; margin-top: 0.25em;">Typos in the California data set....:<br style="box-sizing: border-box;"><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">One Hundred Seventh Street Mag,47 E. 107Th St.,Los Angeles,CA,90003</code><span> </span>should be<span> </span><code class="notranslate" style="box-sizing: border-box; font-family: ui-monospace, SFMono-Regular, &quot;SF Mono&quot;, Menlo, Consolas, &quot;Liberation Mono&quot;, monospace; font-size: 11.9px; padding: 0.2em 0.4em; margin: 0px; background-color: var(--color-neutral-muted); border-radius: 6px;">147 E. 107th St.</code></li></ol></div>

The CSV here contains the data to be reviewed:
[go_pass_schools_merged_with_california_dataset.csv](https://github.com/LACMTA/gopass-lookup/files/9255325/go_pass_schools_merged_with_california_dataset.csv)

### CSV Notes

- `_x` --> means the data is from **Devon's sheet**: https://docs.google.com/spreadsheets/d/1WLoM1h2PtmZpChgMkSDQ4gGOQXe3Y3fc0QKmasgu2pU/edit#gid=1777125641
 
- `_y` --> means the data is from the California schools list.

- I ended up filtering only within Los Angeles County

district_x | district_y | original_name_x | original_name_y | status | school_name | school_name_with_some_districts_attached | participating | address_x | address_y | city_x | city_y | score | duped
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Centinela Valley | Centinela Valley Union High | Hawthorne High | Hawthorne High | Active | Hawthorne High (Centinela Valley) | Hawthorne High | True | 4859 West El Segundo Blvd. | 4859 West El Segundo Blvd. | Hawthorne | Hawthorne | 95.0 | False
Centinela Valley | Centinela Valley Union High | Lawndale High | Lawndale High | Active | Lawndale High (Centinela Valley) | Lawndale High | True | 14901 S. Inglewood Avenue | 14901 South Inglewood Ave. | Lawndale | Lawndale | 86.53465346534652 | False
Centinela Valley | Centinela Valley Union High | Leuzinger High | Leuzinger High | Active | Leuzinger High (Centinela Valley) | Leuzinger High | True | 4118 West Rosecrans Ave. | 4118 West Rosecrans Ave. | Lawndale | Lawndale | 95.0 | False

�

**Comment by matikin9** [comment]
We are attempting to match the schools from Devon's list with the statewide list of schools. We're matching off of these specific fields: 

- District
- School
- Street Address.

In our results we have a few situations where we're not getting a 1-to-1 match between the lists.  This includes 1-to-many matches or no matches found. These issues will require manual reconciliation but will be a one-time process.

## 1-to-many matches

Affects around 30 rows.

This can be because they have different telephone numbers. Do we list the school once but provide multiple phone numbers, or do something else?

Example: 

District | School | Address | City | State | Zip Code | Telephone | Participating
-- | -- | -- | -- | -- | -- | -- | --
Charter | Alliance Gertz-Ressler Richard Merkin 6-12 Complex | 2023 South Union Avenue | Los Angeles | CA | 90007 | (213) 745-8141 | TRUE
Charter | Alliance Gertz-Ressler Richard Merkin 6-12 Complex | 2023 South Union Avenue | Los Angeles | CA | 90007 | (213) 748-0141 | TRUE

A few schools have multiple matches in the state list because it includes closed or merged schools being returned. We can probably ignore closed or merged schools.

## No matches

Affects around 340 rows.

1. One of the fields (District, School, Street Address) do not match.  This is typically due to the Street address having issues because it's formatted differently or incorrect.  Examples:
    - Differences in address formatting: `south` vs. `s` and `Mc Kinley` vs. `McKinley`
    - Typos in the California data set: `47 E. 107Th St.` should be `147 E. 107th St.`

## 1-to-1 matches

Even in the schools where we have made a 1-to-1 match, we see differences in the school name. For example, `109th Street Elementary` is `One Hundred Nineth Street Elementary` in the state list (this is the official spelling: https://109street-lausd-ca.schoolloop.com/). Do we want to combine both names so that it shows up regardless of which version you search for?

Some matched schools are have a status of `closed` in the state dataset and we may want to look into this. For example, there may have been a false match with a similarly named school that is closed. There are some with the status of `merged` as well but that might be okay.

## Website Display

The only data from these sheets we need to display on the website are School Name, Telephone, and possibly District.

School Name will show up in the auto-suggest for the search field.  Because we have some duplicate school names that belong to different districts, we should show the district for disambiguation.  

1. Do we show the district for all schools, or only for the ones where there are duplicate names?
2. Are we okay with the district showing up in parenthesis after the school name?

School Name will show up in the header of the results page.  The mockups show administrator name and phone number as well.  We can try to pull some of this data from this state, how much do we want to show?

![image (2)](https://user-images.githubusercontent.com/1873072/182739875-658bc5d0-afe8-407d-bfde-96f09f1b2960.png)

## CSV Data

The CSV here contains the data to be reviewed:
[go_pass_schools_merged_with_california_dataset.csv](https://github.com/LACMTA/gopass-lookup/files/9255325/go_pass_schools_merged_with_california_dataset.csv)

What counties do we want to include in the auto-suggest list.  Albert found some matching schools that were outside of LA County.

### CSV Notes

- `_x` --> means the data is from **Devon's sheet**: https://docs.google.com/spreadsheets/d/1WLoM1h2PtmZpChgMkSDQ4gGOQXe3Y3fc0QKmasgu2pU/edit#gid=1777125641
 
- `_y` --> means the data is from the California schools list.

- I ended up filtering only within Los Angeles County

district_x | district_y | original_name_x | original_name_y | status | school_name | school_name_with_some_districts_attached | participating | address_x | address_y | city_x | city_y | score | duped
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Centinela Valley | Centinela Valley Union High | Hawthorne High | Hawthorne High | Active | Hawthorne High (Centinela Valley) | Hawthorne High | True | 4859 West El Segundo Blvd. | 4859 West El Segundo Blvd. | Hawthorne | Hawthorne | 95.0 | False
Centinela Valley | Centinela Valley Union High | Lawndale High | Lawndale High | Active | Lawndale High (Centinela Valley) | Lawndale High | True | 14901 S. Inglewood Avenue | 14901 South Inglewood Ave. | Lawndale | Lawndale | 86.53465346534652 | False
Centinela Valley | Centinela Valley Union High | Leuzinger High | Leuzinger High | Active | Leuzinger High (Centinela Valley) | Leuzinger High | True | 4118 West Rosecrans Ave. | 4118 West Rosecrans Ave. | Lawndale | Lawndale | 95.0 | False

**Comment by albertkun** [comment]
Here is the closed matched schools table:

id | district_x | district_y | original_name_x | original_name_y | status | school_name | school_name_with_some_districts_attached | participating | address_x | address_y | city_x | city_y | score | duped
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
75 | Charter | LAUSD | El Camino Real Charter High School | Camino Real High School | Closed | El Camino Real Charter High School (Charter) | El Camino Real Charter High School | True | 5440 Valley Circle Blvd. | 5440 Valley Circle Blvd. | Woodland Hills | Los Angeles | 89.3 | False
139 | El Rancho | El Rancho Unified | Ellen Ochoa Prep Academy | Ellen Ochoa Prep Academy | Closed | Ellen Ochoa Prep Academy (El Rancho) | Ellen Ochoa Prep Academy | True |   | 8110 Paramount Blvd. |   | Pico Rivera | 90 | False
129 | Duarte | Duarte Unified | Andres Duarte Arts Academy (PK-8) | Andres Duarte Arts Academy (PK-8) | Closed | Andres Duarte Arts Academy (PK-8) (Duarte) | Andres Duarte Arts Academy (PK-8) | True | 1433 Crestfield Drive | 1433 Crestfield Dr. | Duarte | Duarte | 91.4728682170543 | False
8 | Charter | LAUSD | Alliance College-Ready Middle Academy 5 | Alliance College-Ready Middle Academy 5 | Closed | Alliance College-Ready Middle Academy 5 (Charter) | Alliance College-Ready Middle Academy 5 | True | 211 South Avenue 20 | 211 South Avenue 20 | Los Angeles | Los Angeles | 92.4242424242424 | False
50 | Charter | LAUSD | Animo Westside | Animo Westside Charter Middle | Closed | Animo Westside (Charter) | Animo Westside | True | 5456 McConnell Ave. | 5456 McConnell Ave. | Los Angeles | Los Angeles | 95 | False
946 | LAUSD | LAUSD | North Hollywood Senior High STEM Magnet | North Hollywood Magnet | Closed | North Hollywood Senior High STEM Magnet (LAUSD) | North Hollywood Senior High STEM Magnet | True | 5231 Colfax Ave | 5231 Colfax Ave. | North Hollywood | North Hollywood | 95 | False
987 | LAUSD | LAUSD | Park Western Pl Elementary Gifted/STEAM Magnet | Park Western Gifted Magnet | Closed | Park Western Pl Elementary Gifted/STEAM Magnet (LAUSD) | Park Western Pl Elementary Gifted/STEAM Magnet | True | 1214 Park Western Pl | 1214 Park Western Pl. | San Pedro | San Pedro | 95 | False
1469 | Pasadena Unified | Pasadena Unified | Pasadena High | Evening High | Closed | Pasadena High (Pasadena Unified) | Pasadena High | True |   | 1505 N. Marengo |   | Pasadena | 95 | False
190 | LAUSD | LAUSD | 4th Street Primary Center DL Two-Way Im Spanish | Fourth Street Primary Center | Closed | 4th Street Primary Center DL Two-Way Im Spanish (LAUSD) | 4th Street Primary Center DL Two-Way Im Spanish (LAUSD) | True | 469 Amalia Ave | 469 Amalia Ave. | Los Angeles | Los Angeles | 87.6923076923077 | True
188 | LAUSD | LAUSD | 4th Street Primary Center | Fourth Street Primary Center | Closed | 4th Street Primary Center (LAUSD) | 4th Street Primary Center (LAUSD) | True | 469 Amalia Ave | 469 Amalia Ave. | Los Angeles | Los Angeles | 94.7368421052632 | True

**Comment by matikin9** [comment]
We good.
